-- Create admin user
-- Run this SQL on your Railway PostgreSQL database

-- First, check if admin exists
SELECT * FROM users WHERE email = 'admin@mail.com';

-- If not exists, insert admin user
-- Password: admin (hashed with bcrypt)
INSERT INTO users (name, email, password) 
VALUES (
    'Admin',
    'admin@mail.com',
    '$2a$10$YourHashedPasswordHere'  -- This will be generated by the backend
)
ON CONFLICT (email) DO NOTHING;

-- Note: You should register the admin user through the signup page first
-- Or use the backend to create it with proper password hashing
